sudo: required
services:
  - docker
before_install:
  - docker build -t wilbax/docker-react -f Dockerfile.dev  .
script:
  - docker run -e CI=true wilbax/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-637423287616"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"