name: deploy Nginx
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          docker build -t asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/mydockerepo/myapp:latest -f Dockerfile.dev  .

      - name: test
        run:
          docker run -e CI=true wilbax/docker-react npm run test
          
      - name: push image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/mydockerepo/myapp:latest